import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "./globals.css";
const publicSans = Public_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-public-sans'
})
export const metadata: Metadata = {
  title: "Faslane",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={publicSans.className}>{children}</body>
    </html>
  )
}